# Generated by Django 5.0.3 on 2024-04-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='clothing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
