# Generated by Django 5.0.3 on 2024-04-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_food_clothing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalappliances',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='groceries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
